### ISSUE TITLE
 Unable to update edit in tasks&notes with an apostrophe(')

### ISSUE THREAD

**Issue by ghost** [Crazy-Marvin/ToDont#66] opened 2021-07-08 03:22 UTC
## :writing_hand: Describe the bug
When a task or note with apostrophe have been edited, click on the update button, the edit will be lost rather than saved.

## :bomb: Steps to reproduce

1. Create a new task and type any content with an apostrophe.
2. Click on save.
3. Edit the note or task and click the update button.
4. The edit is lost rather than saved.

## :wrench: Expected behavior

The edit is saved.
## :iphone: Tech info
- Device:  Huawei p30 pro
- OS:  EMUI10.0
- App Version: 1.1 Beta

**Comment by CrazyMarvin** [comment] 2021-07-08 07:15
Hey, thanks for your bug report. The same happens on my phone too. @arafaatqureshi will have a look into it.

**Comment by ghost** [comment] 2021-07-08 12:34
> Hey, thanks for your bug report. The same happens on my phone too. @arafaatqureshi will have a look into it.

Fine. Thank you. I'm looking forward to its fixing. 🙂

**Comment by CrazyMarvin** [comment] 2021-07-16 21:59
With v1.2 this should be fixed hopefully. Please let us know if that's the case for you. Sorry for the inconvenience.

**Comment by ghost** [comment] 2021-07-29 10:03
> With v1.2 this should be fixed hopefully. Please let us know if that's the case for you. Sorry for the inconvenience.

Still has the problem😅

**Comment by ghost** [comment] 2021-07-29 10:05
Thank you for hard work, it seems this is a complex problem😂

**Comment by CrazyMarvin** [comment] 2021-09-11 21:54
We will have another look. Thanks for your patience. 🙏

By the way, is it possible for you to write an apostrophe in the `Enter Task` field and in the `Note `field it crashes? Or does it crash in both fields for you when entering an apostrophe?

**Comment by arafaatqureshi** [comment] 2021-09-12 07:32
@CrazyMarvin We updated it last time and it was working fine then for apostrophe. Didnt check it for update again. will look into it.

**Comment by CrazyMarvin** [comment] 2021-12-30 21:57
I just checked again and an apostrophe in the task itself (green circle) is working as intended on my device but a note with an apostrophe (red circle) is not saved and causes a crash sometimes.

![apostrophe](https://user-images.githubusercontent.com/15004217/147790567-b63e7dfe-8b53-4f80-81d1-86adbe3195b1.jpg)

**Comment by CrazyMarvin** [comment] 2021-12-30 22:16
An apostrophe in a label causes a crash too.

**Comment by CrazyMarvin** [comment] 2022-01-24 20:06
Does it make a difference for you if you create a label first or not?
I noticed this on my device:

This crashes:
Task created first, then label

This works:
Label created, task afterwards

**Comment by arafaatqureshi** [comment] 2022-01-25 05:16
It's quite strange ,
I'm still looking into it.

**Comment by CrazyMarvin** [comment] 2022-10-04 22:17
@subeep, it would be awesome if you could have a look at this issue too. 😅
Thanks!

**Comment by subeep** [comment] 2022-10-05 12:49
I have solved the problem. I will pull the request as soon as I can fork the project again because of my previous pull there are many changes in my fork and once the pull merges, I can solve this by forking the updated version.

**Comment by CrazyMarvin** [comment] 2022-10-05 14:53
> I have solved the problem. I will pull the request as soon as I can fork the project again because of my previous pull there are many changes in my fork and once the pull merges, I can solve this by forking the updated version.

That are great news. I just merged your existing PR so that you can go on. 😀

**Comment by CrazyMarvin** [comment] 2022-10-05 18:56
Fixed in To Don't v1.9 (closed by #165)

**Closed as completed** 2022-10-05 18:56 UTC
Labels: bug
