### ISSUE TITLE
Crash after click on symbol

### ISSUE THREAD

**Issue by stop5** [Crazy-Marvin/ToDont#29] opened 2021-04-29 23:29 UTC
## :writing_hand: Describe the bug
The app crashes when clicking the symbol left to an habit

## :bomb: Steps to reproduce

1. Create a new bad habit with the +
2. Try to click on one of the symbols at the left side of the habit
3. App crashed

## :iphone: Tech info
- Device: oneplus 7 pro
- OS: Android 11 (Lineageos 18.1)
- Version: 1.0, 1.1 from fdroid

## :page_facing_up: Additional context
Stack Trace:
FATAL EXCEPTION: main
Process: rocks.poopjournal.todont, PID: 9668
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackground(android.graphics.drawable.Drawable)' on a null object reference
	at rocks.poopjournal.todont.Adapters.HabitsAdapter$2.onClick(HabitsAdapter.java:166)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Edit log:
30.05.21 tested it with 1.1

**Comment by CrazyMarvin** [comment] 2021-05-01 21:29
Thanks for reporting the bug, @stop5.
I could reproduce it on another device running Android 11.
May you please have a look, @arafaatqureshi?

**Comment by arafaatqureshi** [comment] 2021-05-02 18:41
Sure @CrazyMarvin .
Thanks @stop5 , will check where the problem is, and will update it.

**Comment by CrazyMarvin** [comment] 2021-12-30 22:07
This bug should be fixed by now.
May you please confirm, @stop5?

**Comment by CrazyMarvin** [comment] 2022-10-04 22:19
I tried again and could not reproduce this bug anymore so I am closing this issue.

**Closed as completed** 2022-10-04 22:19 UTC
Labels: bug
